### ISSUE TITLE
Error about "compute_prior"

### ISSUE THREAD

**Issue by sohey1910** [THUNLP-AIPoet/MixPoet#1]
非常感谢你们团队所做的这项工作！
在我进行训练的时候出现了一个错误，
![image](https://user-images.githubusercontent.com/29793535/78420531-8fe1fe00-7682-11ea-8c27-1295c52c28be.png)
我查看了graph.py文件,在里面没有找到关于compute_prior()函数的定义，希望方便时可以解答下，谢谢~

**Comment by XiaoyuanYi** [comment]
你好，问题已修复。 我们在删除一些调试用的冗余代码时，误删了该函数。如有其他问题欢迎提出。

**Comment by XiaoyuanYi** [comment]
@sohey1910 

你好，问题已修复。 我们在删除一些调试用的冗余代码时，误删了该函数。如有其他问题欢迎提出。

**Comment by sohey1910** [comment]
![image](https://user-images.githubusercontent.com/29793535/78636534-17c24500-78db-11ea-9ebf-3e391cdf0c2a.png)
感谢您的回答，训练的问题已经解决了，但在进行测试的时候，遇到了上面的问题，错误好像是在加载“./data/pingshui_amb.pkl”时出现的，我打开看了下这个文件，内容是这样的：
![image](https://user-images.githubusercontent.com/29793535/78636790-9919d780-78db-11ea-902b-03bd289c23ad.png)
希望方便时能够帮忙看一下这个问题，非常感谢~

**Comment by XiaoyuanYi** [comment]
@sohey1910 
你好， pkl文件是存储为二进制形式的，不能直接当作文本文件读取，需要使用python的pickle包。具体请参见我们源码 codes/filter.py的118~120行

**Comment by XiaoyuanYi** [comment]
@sohey1910 
你好， 我们自己测试时没有问题。这可能是因为pingshui_amb.pkl在下载的过程中文件有损坏。请尝试重新下载pingshui_amb.pkl文件，在下载过程中保持网络通畅。

或者安装git lfs， 然后直接clone：
git lfs clone git@github.com:THUNLP-AIPoet/Datasets.git

**Comment by TTlaozu** [comment]
@XiaoyuanYi 
您好，我在测试时也是发现上述无法找到pingshui_amb.pkl文件这个错误，使用git lfs报如下错误：
Git LFS: (0 of 1 files) 0 B / 115.47 MB                                                                                                                                                     
batch response: Currently only supports Enterprise projects
error: failed to fetch some objects from 'https://gitee.com/ttlaozu/Datasets.git/info/lfs'
希望能够帮忙看一下这个问题，谢谢！
