### ISSUE TITLE
Error About "pingshui_amb.pkl Not Found"

### ISSUE THREAD

**Issue by TTlaozu** [THUNLP-AIPoet/MixPoet#2]
您好，
我在测试加载“./data/pingshui_amb.pkl”时出现错误，
报无法找到pingshui_amb.pkl文件，

后发现这个是大文件，使用git lfs后报如下错误：
Git LFS: (0 of 1 files) 0 B / 115.47 MB
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/THUNLP-AIPoet/Datasets.git/info/lfs'

希望能够帮忙看一下这个问题，谢谢！

**Comment by XiaoyuanYi** [comment]
@TTlaozu 
您好，可能下载次数较多，超过了我们之前的流量限额。现已扩充流量，目前能够正常下载了。如有其他问题欢迎提出。

**Comment by TTlaozu** [comment]
> @TTlaozu
> 您好，可能下载次数较多，超过了我们之前的流量限额。现已扩充流量，目前能够正常下载了。如有其他问题欢迎提出。

model能跑起来了，十分感谢！

**Comment by TTlaozu** [comment]
> @TTlaozu
> 您好，可能下载次数较多，超过了我们之前的流量限额。现已扩充流量，目前能够正常下载了。如有其他问题欢迎提出。

model能跑起来了，十分感谢！
