### ISSUE TITLE
模型收敛问题

### ISSUE THREAD

**Issue by apple55bc** [THUNLP-AIPoet/MixPoet#6]
作者您好~我用这个模型进行了修改，用于数据量和风格更多的文本生成任务。模型结构主要是吧Encoder和Decoder置换为Transformer结构，其它没有变更。但是似乎很难收敛。不知道作者有尝试过Transformer结构的Mixpoet吗？

此外对于源论文，我有一些疑问想请教下：
1：隐层z的信息，是仅包含Factor信息，还是包含了Factor和Context信息？如果是后者，对抗训练如何保证隐层z对于Prior可以学到Context信息呢？换句话说，判别器似乎只能通过已知的Factor标签来判别Prior和Poesterior输出的z在factor信息上的准确度。
2：生成器同时优化Poesterior和Prior，是否可能会使得Poesterior蕴含的Context信息退化？因为只需要两个输出的z都是无效信息，就可以完美的欺骗判别器了。（这个问题在训练过程中有体现，只有锁住生成器的Poesterior更新梯度才能保留Poesterior输出的z所包含的context信息）
3：如果z已经包含了足够的Factor和Context信息，最后输出给Decoder的时候为什么需要把w（key_word）和y（factor label）信息与z进行拼接了？因为这样做就无法证明Decoder中到底是z在起作用，还是k和y在起作用了。

期待您的解答 ^-^

**Comment by XiaoyuanYi** [comment]
@apple55bc 
您好, 感谢提问. 回复如下:

1. 关于收敛问题. 我们尚未尝试过Transformer为基础的结构, 相关试验都是在LSTM上做的. 在我们task上, 收敛困难可能是以下原因:

(1) 有标注数据不足. 我们实验中发现有标注和无标注数据比例在1:3左右比较合适. 我们尝试过将标注数据量减少为原来的10%~20%, 发现在原本的参数下收敛变难. 可能的话,  请尝试增加标注数据或者减少未标注数据试一下.

(2) Transformer encoder可能会使得文本x的表示变强, 进而影响判别器的判别. 这里具体要看判别器以及生成器的loss变化情况,可能是其中一方过弱/过强. 如果是这个问题, 可以考虑使用更强/更弱的判别器. 另外可以调一下config.py里的noise_decay_steps. 我们在判别器训练时注入噪音. 因为在我们的实验中一直是判别器过强, 所以采用了增加噪音, spectral normalization 等多种方式规范判别器. 如果判别器过弱, 可以考虑把这些trick都去掉.

2. 关于文本(您所说的context)信息x. 
prior中不含x的信息, 而poesterior会含有. 隐变量z的作用只是捕捉w和属性y的信息, 生成时使用的先验p(z|y,w)无法也并不需要包含x.  可以理解为在poesterior p(z|x,y,w)的学习中, x只是用来帮助更好地构建属性的表示, 因为如果仅仅只用y的话, 模型在encoder层面无法直接构建起具体的文本空间x与对应的label y之间的联系. 我们所用的判别器Eq.(10)是conditional GAN里常用的一种方式, 即把label信息y一起输入到判别器中, 这样可以在一定程度上保证到的z能够包含y的信息. 或者更广泛地说, 先验和后验share的条件都可以一起加入进去. 所以其实可以考虑把w也和y一并输入判别器, 这样可能会增加z中topic的信息占比, 从而有利于文本中topic word的生成.不过我们当时试验比较匆忙, 尚未尝试这一点.


3. 关于信息退化,
这是一个很好的问题. 在早期的VAE中存在kl vanishing问题, 即kl散度降低为0, 如果采用简单的正太作为先验, 则后验会完全退化为与conditional无关的先验. 但在我们的实验中发现, kl并不会降为0. 请看一下Mixpoet/pictures/p4.png, 我们画出了实验中生成器和判别器的loss, 以及先验和后验的距离(依据一组采样点计算得出). 可以看到先验和后验在接近但是并没有降到0, 同时判别器和生成器的loss也没有相交, 即Eq.(10)中的近似KL虽然在变小但是仍大于0. 实际上的效果表现为, 先验向后验靠近, 使得其对应的z更加接近后验中和x对齐的z; 同时后验向先验靠近, z的解耦性更好. 后验中包含x的信息是在reconstruction loss中保证的, 由于decoder为p(x|z, w, y) (Eq.(6)), condition中能够提供x相关信息的只有z, 所以模型必须学到在后验z中包含一定的x信息, 才能成功重构原本的x. 不过由于autoregressive式生成, decoder本身太强, 有时可能会依赖于前序序列来生成高概率的内容从而忽略z, 对这一问题也有很多办法解决, 例如BOW loss, word dropout等, 我们在Sec. 3.4有提到.


4. 关于deocder
确实可能会有这个问题 囧 但是本身导出的lower bound里, decoder就具有p(x|z, w, y)的形式, 数学上无法直接把w和y扔掉. 所以一般在conditional VAE里, 都会把condition和z一起输入deocder. 不过相比z, 一般y的维度较小. 例如我们的实验里, z是256维, y是64维度. 在一些图片生成的模型中, y可能是10维的one-hot, 所以一般z会占主导作用. 对我们的模型来说, 也可以考虑直接把y设为2维/3维的one-hot, 或者降低w和y的embedding的维数, 以此来增加model对z的依赖.


希望以上信息对您有帮助~

**Comment by apple55bc** [comment]
非常感谢回复这么多内容，很有帮助，赞！
不过还有一个疑问，关于z中，如果判别器没有x或者w的信息，在后验网络的z可以通过reconstruction-loss来获得x的信息，但是生成器的z似乎没有任何梯度来获取x或者w的信息？我理解的低维空间任何一个分布都是合理的，判别器在没有w和x信息的情况无法区分哪一个z是合理的？如果是这样，预测时候的z应该只会包含factors。

**Comment by XiaoyuanYi** [comment]
@apple55bc  
是的, 生成器的z有w的信息, 但是并没有x的信息, 同时对判别器我们也没有输入x.  所以判别器区分只是依据(或者说我们期望它依据)解耦性来进行判断, 从而优化KL散度并实现解耦.  所以如果是用Transformer的话, 有可能Transformer-encoder得到的文本表示x太强,  从而使得后验的z(带x信息)和先验的z(不带x信息)分布上距离很难拉近, KL降不下去, 进而难以收敛.  

"如果是这样，预测时候的z应该只会包含factors。" 您说的"预测"是指decoder实际产生诗歌吗?

**Comment by apple55bc** [comment]
是的，经过prior网络和decoder生成的诗词。z是说的prior输出的z。

**Comment by XiaoyuanYi** [comment]
@apple55bc  嗯嗯是的, 训练时我们用的是后验的z.  生成诗歌时用的是先验的z, 此时因为诗歌还未生成, 本身并无法得到确切的x的信息, 所以用的是先验

**Comment by apple55bc** [comment]
哦，知道了。多谢！

**Comment by XiaoyuanYi** [comment]
@apple55bc  好的, 那这个issue我就先关闭了. 如果还有其他问题,  欢迎新开个issue或者邮件我都行,  祝您的研究一切顺利~
