### ISSUE TITLE
MixPoet可以实现律诗吗？

### ISSUE THREAD

**Issue by hsaigei** [THUNLP-AIPoet/MixPoet#8]
老师你好， 最近在学习MixPoet。想问下MixPoet能否通过修改sens_num的长度来实现律诗的写作？我尝试了一下会出现一下问题
![image](https://user-images.githubusercontent.com/37724774/107199440-611a7e00-6a31-11eb-8fce-a84afc612c2e.png), 问下如果要让MixPoet也可以实现律诗功能改怎么修改？

**Comment by XiaoyuanYi** [comment]
@hsaigei  你好, Mixpoet暂不支持律诗的生成. 因为代码训练及格律模式目前都只实现了绝句版本.  此外Mixpoet是基于LSTM构建的, 从我们的经验来看,  如果不加额外的机制设计, LSTM无法很好地学到律诗中的对仗.  不过我们近期会对Mixpoet做一次改进, 届时会在训练及生成上兼容不同句子数, 请关注我们的github, 我们会争取尽快更新.
